# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowjs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowfile',
            name='state',
            field=models.IntegerField(choices=[(1, 'Uploading'), (2, 'Completed'), (3, 'Upload Error'), (4, 'Joining chunks'), (5, 'Joining chunks error')], default=1),
        ),
    ]
